INSERT INTO TEAM (team_name, team_country)
VALUES 
('Atlético Madrid', 'Spain'),
('Sevilla', 'Spain'),
('Manchester United', 'England'),
('Liverpool', 'England'),
('Bayern Munich', 'Germany'),
('Borussia Dortmund', 'Germany'),
('Paris Saint-Germain', 'France'),
('Marseille', 'France'),
('Juventus', 'Italy'),
('AC Milan', 'Italy'),
('Inter Milan', 'Italy'),
('Napoli', 'Italy'),
('Ajax', 'Netherlands'),
('PSV Eindhoven', 'Netherlands'),
('Porto', 'Portugal'),
('Benfica', 'Portugal'),
('Celtic', 'Scotland'),
('Rangers', 'Scotland'),
('Galatasaray', 'Turkey'),
('Fenerbahçe', 'Turkey'),
('Shakhtar Donetsk', 'Ukraine'),
('Dynamo Kyiv', 'Ukraine'),
('River Plate', 'Argentina'),
('Boca Juniors', 'Argentina'),
('Sao Paulo', 'Brazil'),
('Flamengo', 'Brazil'),
('Corinthians', 'Brazil'),
('Palmeiras', 'Brazil'),
('Sydney FC', 'Australia'),
('Melbourne Victory', 'Australia'),
('Kashima Antlers', 'Japan'),
('Urawa Reds', 'Japan'),
('Red Bull Salzburg', 'Austria'),
('Rapid Wien', 'Austria'),
('Club Brugge', 'Belgium'),
('Anderlecht', 'Belgium'),
('Rosenborg', 'Norway'),
('Molde', 'Norway'),
('FC Copenhagen', 'Denmark'),
('Brøndby IF', 'Denmark'),
('HJK Helsinki', 'Finland'),
('Malmo FF', 'Sweden'),
('AIK', 'Sweden'),
('Spartak Moscow', 'Russia'),
('CSKA Moscow', 'Russia'),
('Al Hilal', 'Saudi Arabia'),
('Al Nassr', 'Saudi Arabia'),
('Zamalek', 'Egypt'),
('Al Ahly', 'Egypt'),
('Esperance de Tunis', 'Tunisia'),
('Wydad Casablanca', 'Morocco'),
('Kaizer Chiefs', 'South Africa'),
('Orlando Pirates', 'South Africa'),
('New York Red Bulls', 'USA'),
('LA Galaxy', 'USA'),
('Toronto FC', 'Canada'),
('CF Montréal', 'Canada'),
('Tigres UANL', 'Mexico'),
('Club América', 'Mexico'),
('Al Sadd', 'Qatar'),
('Shanghai Port', 'China'),
('Guangzhou FC', 'China');
